# Generated by Django 3.0.7 on 2020-06-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('moving_from', models.CharField(max_length=255)),
                ('house_size', models.CharField(max_length=255)),
                ('is_moved_up', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('moving_into', models.CharField(max_length=255)),
                ('next_house_size', models.CharField(max_length=255)),
                ('next_is_moved_up', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('next_address', models.CharField(max_length=255)),
                ('extra_items', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('additional_service', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
