# Generated by Django 3.0.7 on 2020-06-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmodel',
            options={'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='additional_service',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='extra_items',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Any extra heavy/fragile items'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='is_moved_up',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Need items moved up and down'),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='next_is_moved_up',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Next house need items moved up and down'),
        ),
    ]
